# Generated by Django 3.1.3 on 2020-12-05 18:28

from django.db import migrations, models
import workout.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trenirovka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название тренировки.')),
                ('desc', models.TextField(verbose_name='Описание тренировки.')),
                ('video', models.ImageField(upload_to=workout.models.Trenirovka.load_video, verbose_name='Тренировка.')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'db_table': 'trenirovka',
            },
        ),
    ]
