# Generated by Django 3.1.3 on 2020-12-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trenirovka', '0003_auto_20201220_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trenirovka',
            name='descriptionYoga',
            field=models.TextField(default='', verbose_name='ОписаниеЙога'),
        ),
    ]
