# Generated by Django 3.1.3 on 2020-12-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trenirovka', '0004_auto_20201220_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trenirovka',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
