# Generated by Django 3.1.3 on 2020-12-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trenirovka', '0005_auto_20201220_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trenirovka',
            name='descriptionYoga',
        ),
        migrations.RemoveField(
            model_name='trenirovka',
            name='yoga',
        ),
    ]
