# Generated by Django 3.1.3 on 2020-12-21 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('trenirovka', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesView',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trenirovka.category')),
            ],
            bases=('trenirovka.category', django.views.generic.base.View),
        ),
        migrations.AddField(
            model_name='trenirovka',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trenirovka.category', verbose_name='Категория'),
        ),
    ]
