# Generated by Django 3.1.3 on 2020-12-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trenirovka', '0008_auto_20201221_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trenirovka',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='treny',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trenirovka.trenirovka', verbose_name='Категория'),
        ),
    ]
