# Generated by Django 3.1.3 on 2020-12-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trenirovka', '0009_auto_20201221_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='treny',
        ),
        migrations.AddField(
            model_name='trenirovka',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trenirovka.category', verbose_name='Категория'),
        ),
    ]
